name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Ramazan-yildirim
          outputs: dist/github-contribution-grid-snake.svg
          
          # Arka plan rengi - GitHub'ın orijinal renkleri
          color_bg: '#0d1117'      # GitHub dark theme arka plan
          color_border: '#30363d'  # Karelerin kenar rengi
          
          # Katkı karelerinin renkleri (GitHub'ın orijinal gradient'i)
          colors: |
            '#0d1117'      # Boş kareler (arkaplanla aynı)
            '#0e4429'      # Çok az katkı
            '#006d32'      # Az katkı
            '#26a641'      # Orta katkı
            '#39d353'      # Çok katkı

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
