name: Generate Snake with Custom Colors

on:
  workflow_dispatch:
    # Manuel çalıştırma
  schedule:
    - cron: "0 0 * * *"  # Her gün çalıştırmak istersen

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: nao-pon/gh-contributions-snake@v1
        with:
          github_user_name: Ramazan-yildirim
          outputs: dist/github-contribution-grid-snake.svg
          color_bg: '#0d1117'      # Boş kareler
          color_border: '#30363d'  # Karelerin sınırları
          colors: '#0d1117,#ff6f61,#ffb347,#ffd700,#00bfff'  # Dilediğin renkler

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
